name: "Create .NET artifacts"
description: ""
inputs:
  assembly:
    required: true
    description: ""
  version:
    required: true
    description: ""
  platform:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: Collect artifacts
      shell: bash
      run: |
        # copy artifacts
        mkdir -p ./dist/${{ inputs.assembly }}/
        cp -r ./src/${{ inputs.assembly }}/bin/Release/net8.0/* ./dist/${{ inputs.assembly }}/

        cd ./dist/${{ inputs.assembly }}

        # cleanup debug and localization files
        rm *.pdb
        rm -rf BuildHost*/ cs/ de/ es/ fr/ it/ ja/ ko/ pl/ pt-BR/ ru/ tr/ zh*/

    - name: Get working platform
      id: platform
      shell: bash
      run: |
        PLATFORM=$(echo ${{ inputs.platform }} | sed 's/-.*//')
        echo "platform=$PLATFORM" >> $GITHUB_OUTPUT

    - name: Archive artifact (Linux, macOS)
      shell: bash
      run: |
        cd ./dist
        which pwsh && pwsh -Command Compress-Archive -Path ./${{ inputs.assembly}}/ -DestinationPath ${{ inputs.assembly }}-${{ steps.platform.outputs.platform }}-${{ inputs.version }}.zip || true
        which zip && zip -r ${{ inputs.assembly }}-${{ steps.platform.outputs.platform }}-${{ inputs.version }}.zip ./${{ inputs.assembly}}/ || true
        find ./ -type f -name '*.zip'

    - name: Collect artifacts
      shell: bash
      run: |
        rm -rf ./dist/${{ inputs.assembly }}/
