name: Build with .NET

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NuGet dependencies
        uses: ./.github/composite/nodejs

      - name: Build
        run: |
          dotnet build ./src/Plana.sln --no-restore --configuration=Release
