name: Unit Test with .NET

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NuGet dependencies
        uses: ./.github/composite/setup-dotnet
        with:
          os: ${{ matrix.os }}

      - name: Build
        uses: ./.github/composite/build-dotnet
        with:
          os: ${{ matrix.os }}

      - name: Test
        run: |
          dotnet test ./src/Plana.sln --no-restore --verbosity=normal  --collect="XPlat Code Coverage" --results-directory=./coverage

      - name: Publish Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: matrix.os == 'ubuntu-latest'
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
